-- ===========================================================================
-- Glim curated seed v3 - replacements for 16 video-less backfill targets.
-- Safe to re-run: every statement is INSERT OR IGNORE.
--
-- Scope: video-available replacements only. Do not run against remote D1.
-- All replacement apps have public YouTube videos verified by oEmbed.
-- ===========================================================================

INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at)
VALUES ('glim-system', 'Glim', 'system@glim.app', 1, 1780790400000, 1780790400000);

INSERT OR IGNORE INTO apps (
  id, slug, name, tagline, description, url,
  demo_video_url, youtube_url, thumbnail_url, category, tags,
  maker_id, maker_name, maker_links,
  guest_mode_available, no_login_trial_available, embeddable,
  platform, store_urls, status, icon_url,
  follower_count, save_count, created_at, updated_at
) VALUES
('curated-andalus-institute','andalus-institute','Andalus Institute','A $1M/year education platform built and iterated with Lovable.','Andalus Institute is an online education platform for Islamic studies and Arabic learning. Lovable featured Muhammad Al Andalusi explaining how he used AI app building to move fast while scaling a serious education business.','https://www.andalusinstitute.com',NULL,'https://www.youtube.com/watch?v=A2Koc0TNXqA','https://www.andalusinstitute.com/lovable-uploads/1f9ef20d-2c98-4642-b121-48f7683d5576.png','Education','["education","courses","lovable"]','glim-system','Muhammad Al Andalusi','{"website":"https://www.andalusinstitute.com"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781380000000,1781380000000),
('curated-brickwise-ai','brickwise-ai','Brickwise AI','AI property management automation that made it into Y Combinator.','Brickwise AI automates maintenance workflows for landlords and estate agents. Lovable featured founder Ismail Jeilani on the path from AI-built product to YC.','https://www.brickwiseai.com',NULL,'https://www.youtube.com/watch?v=_lEj4aNHAzw','https://www.brickwiseai.com/og-image.png','Finance','["real-estate","property","yc"]','glim-system','Ismail Jeilani','{"website":"https://www.brickwiseai.com"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781380600000,1781380600000),
('curated-tableone','tableone','TableOne','Restaurant reservation access built from a Lovable landing page.','TableOne helps diners get hard-to-book restaurant reservations in major US cities. Its launch story is a clean example of a fast AI-built product surface turning into real customer demand.','https://tableone.app/',NULL,'https://www.youtube.com/watch?v=_FDxVg-1UAc','https://tableone.app/image.png','Other','["restaurants","reservations","marketplace"]','glim-system','Tarek Arafat','{"website":"https://tableone.app/","x":"https://x.com/tarekarafat_"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781381200000,1781381200000),
('curated-daymaker','daymaker','Daymaker','A physical GTM tool for branded cake drops and gifting campaigns.','Daymaker turns branded cakes and physical moments into a go-to-market channel. Lovable featured William Lindholm on using AI building to grow a $150K/year cake business.','https://www.daymaker.com/',NULL,'https://www.youtube.com/watch?v=9m7_OIhJEGM','https://daymaker.com/brand/og-hero.png','Content','["gifting","commerce","campaigns"]','glim-system','William Lindholm','{"website":"https://www.daymaker.com/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781381800000,1781381800000),
('curated-tradematch','tradematch','TradeMatch','A CRM and matching system for car dealerships.','TradeMatch gives dealerships one system for vehicle sourcing, matching, and customer workflows. Lovable documented the founders building the CRM with AI-assisted product work.','https://tradematch.com',NULL,'https://www.youtube.com/watch?v=kA2zS6KqlxE','https://image.thum.io/get/width/900/crop/1600/noanimate/https://tradematch.com','Productivity','["crm","cars","dealerships"]','glim-system','Erik Sonesson and Pierre Nordstrom','{"website":"https://tradematch.com"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781382400000,1781382400000),
('curated-avenyr','avenyr','Avenyr','A creator-content platform scaling to $7K/month with Lovable.','Avenyr helps teams refine creator marketing workflows and campaign production. Lovable featured the founders on building a revenue-generating platform with AI.','https://avenyr.se',NULL,'https://www.youtube.com/watch?v=58Ef3OCoHYc','https://storage.googleapis.com/gpt-engineer-file-uploads/fnKephtxG6XtUiZaCvc4wusTfZX2/social-images/social-1779200557062-avenyr-graph-image.webp','Content','["creators","marketing","workflow"]','glim-system','Leonardo Ljoljo and Markus Ljungcrantz','{"website":"https://avenyr.se"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781383000000,1781383000000),
('curated-renamify','renamify','Renamify','AI-powered bulk file renaming for messy photo libraries.','Renamify uses AI to rename photos and files locally, turning camera-roll chaos into searchable filenames. Harry Roper documented how the Lovable-built startup reached 40K users.','https://renamify.co',NULL,'https://www.youtube.com/watch?v=ggzFQhTws1M','https://renamify.co/og-image.png','Productivity','["photos","files","ai"]','glim-system','Harry Roper','{"website":"https://renamify.co","x":"https://x.com/harryroper"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781383600000,1781383600000),
('curated-vortex-chaser','vortex-chaser','Vortex Chaser','A storm-intercept driving game built for Vibe Jam 2026.','Vortex Chaser is a high-fidelity tornado interceptor game where players drive, boost, drift, and chase massive supercells through a web-based experience.','https://vortex-chaser.vercel.app',NULL,'https://www.youtube.com/watch?v=Q1wq-SnsdRc','https://vortex-chaser.vercel.app/og-image.png','Game','["vibejam","driving","weather"]','glim-system','Chie Waters','{"website":"https://vortex-chaser.vercel.app"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781384200000,1781384200000),
('curated-rusthaven','rusthaven','Rusthaven','A robotics adventure game where players design, wire, code, and battle robots.','Rusthaven turns robotics and programming into a browser-playable adventure: complete missions, collect parts, wire circuits, write code, and test robots in battle.','https://www.menuliomiestas.lt',NULL,'https://www.youtube.com/watch?v=QFVG4YC0Bxk','https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.menuliomiestas.lt','Game','["robotics","programming","vibejam"]','glim-system','Menulio Miestas','{"website":"https://www.menuliomiestas.lt"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781384800000,1781384800000),
('curated-daily-writer-habit','daily-writer-habit','Daily Writer Habit','A minimalist writing habit tracker built with Bolt.new.','Daily Writer Habit gives doctoral students and long-project writers daily prompts, streak tracking, reminders, and a journal archive to make writing consistent.','https://daily-writer-habit.netlify.app',NULL,'https://www.youtube.com/watch?v=bi-pWSLjsPo','https://image.thum.io/get/width/900/crop/1600/noanimate/https://daily-writer-habit.netlify.app','Productivity','["writing","habits","bolt"]','glim-system','Meredith Hurston','{"website":"https://daily-writer-habit.netlify.app"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781385400000,1781385400000),
('curated-nutrisim','nutrisim','NutriSim','An AI patient simulator for nutrition counseling practice.','NutriSim lets dietitians practice with AI-powered patient scenarios, bridging the gap between classroom nutrition theory and real counseling conversations.','https://nutrition-guidance-sim.netlify.app',NULL,'https://www.youtube.com/watch?v=14XAy1LbG2s','https://nutrition-guidance-sim.netlify.app/og-image.png','Health','["nutrition","simulation","education"]','glim-system','AI Meal Research Institute','{"website":"https://nutrition-guidance-sim.netlify.app"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781386000000,1781386000000),
('curated-seal-codes','seal-codes','seal.codes','Digital seals that prove document authenticity with QR attestations.','seal.codes brings royal-style seals into the digital age: QR code attestations that prove document authenticity through social identity verification.','https://seal.codes',NULL,'https://www.youtube.com/watch?v=luM8w6iVzq8','https://image.thum.io/get/width/900/crop/1600/noanimate/https://seal.codes','DevTools','["documents","verification","security"]','glim-system','Oliver J','{"website":"https://seal.codes"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781386600000,1781386600000),
('curated-poll-spark-stream','poll-spark-stream','Poll Spark Stream','A live polling demo vibe-coded during a CX tooling session.','Poll Spark Stream is a lightweight live polling experience built in a public vibe-coding session for digital customer-experience teams.','https://poll-spark-stream.lovable.app',NULL,'https://www.youtube.com/watch?v=gFr5xymsLKU','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/81d79b6d-6261-4813-9677-a9e361a8949e/id-preview-1e6b4249--3d9a5702-1448-4f20-b235-0cdf7f605552.lovable.app-1772412444866.png','Social','["polls","cx","lovable"]','glim-system','The Digital CX Podcast','{"website":"https://poll-spark-stream.lovable.app"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781387200000,1781387200000),
('curated-selfsnap','selfsnap','SelfSnap','A browser photobooth app vibe-coded in 24 hours.','SelfSnap is a mobile-friendly browser photobooth: open, shoot, and save photos without logins, uploads, or a database.','https://selfsnap.darladavid.com/',NULL,'https://www.youtube.com/watch?v=dKt2zKtm6m0','https://image.thum.io/get/width/900/crop/1600/noanimate/https://selfsnap.darladavid.com/','Content','["photobooth","camera","vue"]','glim-system','Darla David','{"website":"https://selfsnap.darladavid.com/","github":"https://github.com/darladvd/selfsnap-project"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781387800000,1781387800000),
('curated-weight-coach','weight-coach','Weight Coach','A voice-powered AI meal planning assistant built for the Bolt hackathon.','Weight Coach is an AI kitchen assistant that turns meal planning into a guided, voice-first flow for everyday nutrition decisions.','https://weight.coach',NULL,'https://www.youtube.com/watch?v=Udd6o-H9C3U','https://weight.coach/logo.png','Health','["meal-planning","voice","ai"]','glim-system','Sergiy Dybskiy','{"website":"https://weight.coach"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781388400000,1781388400000),
('curated-serenity-ai-wellbeing','serenity-ai-wellbeing','Serenity','An AI-enhanced mindfulness platform with meditation, movement, and wellness flows.','Serenity combines meditation, movement, and mental-wellness flows in an AI-assisted product studio build. The public app exposes both a landing page and app surface.','https://ai-wellbeing-app.netlify.app/app',NULL,'https://www.youtube.com/watch?v=MWNo8wY1dtw','https://image.thum.io/get/width/900/crop/1600/noanimate/https://ai-wellbeing-app.netlify.app/app','Health','["mindfulness","wellness","ai"]','glim-system','Bhuvaneshwari Mallesh','{"website":"https://ai-wellbeing-app.netlify.app/app"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781389000000,1781389000000);

INSERT OR IGNORE INTO posts (
  id, app_id, author_id, type, status, media_type,
  video_url, image_urls, image_captions, thumbnail_url, caption,
  like_count, comment_count, created_at
) VALUES
('post-curated-andalus-institute','curated-andalus-institute','glim-system','official','published','images',NULL,'["https://www.andalusinstitute.com/lovable-uploads/1f9ef20d-2c98-4642-b121-48f7683d5576.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.andalusinstitute.com"]','["Official site artwork","Live homepage screenshot"]','https://www.andalusinstitute.com/lovable-uploads/1f9ef20d-2c98-4642-b121-48f7683d5576.png','A $1M/year education platform built and iterated with Lovable.',0,0,1781380060000),
('post-curated-brickwise-ai','curated-brickwise-ai','glim-system','official','published','images',NULL,'["https://www.brickwiseai.com/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.brickwiseai.com"]','["Official product preview","Live homepage screenshot"]','https://www.brickwiseai.com/og-image.png','AI property management automation that made it into Y Combinator.',0,0,1781380660000),
('post-curated-tableone','curated-tableone','glim-system','official','published','images',NULL,'["https://tableone.app/image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://tableone.app/"]','["Official product preview","Live homepage screenshot"]','https://tableone.app/image.png','Restaurant reservation access built from a Lovable landing page.',0,0,1781381260000),
('post-curated-daymaker','curated-daymaker','glim-system','official','published','images',NULL,'["https://daymaker.com/brand/og-hero.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.daymaker.com/"]','["Official hero artwork","Live homepage screenshot"]','https://daymaker.com/brand/og-hero.png','A physical GTM tool for branded cake drops and gifting campaigns.',0,0,1781381860000),
('post-curated-tradematch','curated-tradematch','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://tradematch.com"]','["Live homepage screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://tradematch.com','A CRM and matching system for car dealerships.',0,0,1781382460000),
('post-curated-avenyr','curated-avenyr','glim-system','official','published','images',NULL,'["https://storage.googleapis.com/gpt-engineer-file-uploads/fnKephtxG6XtUiZaCvc4wusTfZX2/social-images/social-1779200557062-avenyr-graph-image.webp","https://image.thum.io/get/width/900/crop/1600/noanimate/https://avenyr.se"]','["Official product preview","Live homepage screenshot"]','https://storage.googleapis.com/gpt-engineer-file-uploads/fnKephtxG6XtUiZaCvc4wusTfZX2/social-images/social-1779200557062-avenyr-graph-image.webp','A creator-content platform scaling to $7K/month with Lovable.',0,0,1781383060000),
('post-curated-renamify','curated-renamify','glim-system','official','published','images',NULL,'["https://renamify.co/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://renamify.co"]','["Official product preview","Live homepage screenshot"]','https://renamify.co/og-image.png','AI-powered bulk file renaming for messy photo libraries.',0,0,1781383660000),
('post-curated-vortex-chaser','curated-vortex-chaser','glim-system','official','published','images',NULL,'["https://vortex-chaser.vercel.app/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://vortex-chaser.vercel.app"]','["Official game preview","Live gameplay page screenshot"]','https://vortex-chaser.vercel.app/og-image.png','A storm-intercept driving game built for Vibe Jam 2026.',0,0,1781384260000),
('post-curated-rusthaven','curated-rusthaven','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.menuliomiestas.lt"]','["Live project page screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.menuliomiestas.lt','A robotics adventure game where players design, wire, code, and battle robots.',0,0,1781384860000),
('post-curated-daily-writer-habit','curated-daily-writer-habit','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://daily-writer-habit.netlify.app"]','["Live app screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://daily-writer-habit.netlify.app','A minimalist writing habit tracker built with Bolt.new.',0,0,1781385460000),
('post-curated-nutrisim','curated-nutrisim','glim-system','official','published','images',NULL,'["https://nutrition-guidance-sim.netlify.app/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://nutrition-guidance-sim.netlify.app"]','["Official product preview","Live app screenshot"]','https://nutrition-guidance-sim.netlify.app/og-image.png','An AI patient simulator for nutrition counseling practice.',0,0,1781386060000),
('post-curated-seal-codes','curated-seal-codes','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://seal.codes","https://image.thum.io/get/width/900/crop/1600/noanimate/https://seal.codes/hackathon"]','["Live homepage screenshot","Hackathon showcase screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://seal.codes','Digital seals that prove document authenticity with QR attestations.',0,0,1781386660000),
('post-curated-poll-spark-stream','curated-poll-spark-stream','glim-system','official','published','images',NULL,'["https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/81d79b6d-6261-4813-9677-a9e361a8949e/id-preview-1e6b4249--3d9a5702-1448-4f20-b235-0cdf7f605552.lovable.app-1772412444866.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://poll-spark-stream.lovable.app"]','["Product preview image","Live polling screenshot"]','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/81d79b6d-6261-4813-9677-a9e361a8949e/id-preview-1e6b4249--3d9a5702-1448-4f20-b235-0cdf7f605552.lovable.app-1772412444866.png','A live polling demo vibe-coded during a CX tooling session.',0,0,1781387260000),
('post-curated-selfsnap','curated-selfsnap','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://selfsnap.darladavid.com/"]','["Live photobooth screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://selfsnap.darladavid.com/','A browser photobooth app vibe-coded in 24 hours.',0,0,1781387860000),
('post-curated-weight-coach','curated-weight-coach','glim-system','official','published','images',NULL,'["https://weight.coach/logo.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://weight.coach"]','["Official app logo","Live homepage screenshot"]','https://weight.coach/logo.png','A voice-powered AI meal planning assistant built for the Bolt hackathon.',0,0,1781388460000),
('post-curated-serenity-ai-wellbeing','curated-serenity-ai-wellbeing','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://ai-wellbeing-app.netlify.app/app","https://image.thum.io/get/width/900/crop/1600/noanimate/https://ai-wellbeing-app.netlify.app/"]','["Live app screenshot","Landing page screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://ai-wellbeing-app.netlify.app/app','An AI-enhanced mindfulness platform with meditation, movement, and wellness flows.',0,0,1781389060000);
