-- ===========================================================================
-- Glim curated seed v2 - 22 additional vibe-coded apps + 1 official post each.
-- Safe to re-run: every statement is INSERT OR IGNORE.
--
-- Scope: deliverable 1 only. Do not run against remote D1.
-- ===========================================================================

INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at)
VALUES ('glim-system', 'Glim', 'system@glim.app', 1, 1780790400000, 1780790400000);

INSERT OR IGNORE INTO apps (
  id, slug, name, tagline, description, url,
  demo_video_url, youtube_url, thumbnail_url, category, tags,
  maker_id, maker_name, maker_links,
  guest_mode_available, no_login_trial_available, embeddable,
  platform, store_urls, status, icon_url,
  follower_count, save_count, created_at, updated_at
) VALUES
('curated-plinq','plinq','Plinq','Instant safety checks from public records for women in Brazil.','Plinq turns public criminal and legal records into consumer safety checks for women in Brazil, with risk flags and emergency workflows. Sabrine Matos, a growth marketer without a technical background, built it with Lovable in 45 days and grew it past 10K users.','https://lp.plinq.com.br/',NULL,NULL,'https://lp.plinq.com.br/plinq_pink_black.png','Social','["safety","women","brazil"]','glim-system','Sabrine Matos','{"website":"https://lp.plinq.com.br/","x":"https://www.linkedin.com/in/sabrineamatos/en"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781301000000,1781301000000),
('curated-betriqai','betriqai','BetriqAI','AI sports predictions with match forecasts and real-time analytics.','BetriqAI packages machine-learning match forecasts, data-driven picks, and sports analytics into a polished Lovable-built product experience.','https://www.betriqai.com/',NULL,NULL,'https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/dc442780-12c8-4ea0-b285-6692f7af66fb/id-preview-ab9a2ca1--cedd0149-ff2c-4ff9-9b36-dae4ef207c95.lovable.app-1773807748624.png','AI','["sports","predictions","ai"]','glim-system','BETRIQ AI','{"website":"https://www.betriqai.com/","x":"https://x.com/betriqAI"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781304600000,1781304600000),
('curated-tastly','tastly','Tastly','An installable AI cookbook for saving, cooking, and sharing recipes.','Tastly is a smart cookbook that imports recipes from URLs, magazine photos, or AI prompts, then organizes them into a shareable cooking library.','https://tastly.ai/',NULL,NULL,'https://tastly.ai/og-image.png','Content','["recipes","cooking","ai"]','glim-system','Anonymous Maker','{"website":"https://tastly.ai/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781308200000,1781308200000),
('curated-pathcraft','pathcraft','PathCraft','Roll dice, build the road, and race across a board you invented.','PathCraft is a compact Lovable-built board-racing game: dice rolls create the path, players adapt, and each race produces a new route.','https://roll-a-path.lovable.app/',NULL,NULL,'https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/9a1d4ca8-9af1-446a-92bc-512fecfa5f2c/id-preview-b2fb7158--ca4ac090-3d04-4f62-af7a-19d8544bda3e.lovable.app-1779745560137.png','Game','["game","board","racing"]','glim-system','Anonymous Maker','{"website":"https://roll-a-path.lovable.app/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781311800000,1781311800000),
('curated-wanderscout','wanderscout','WanderScout','AI travel search that finds destinations matching your constraints.','WanderScout flips travel search around: describe the trip constraints first, then get destination ideas that actually match weather, budget, season, and vibe.','https://wanderscout.app/',NULL,NULL,'https://wanderscout.app/og-image.png','Other','["travel","search","ai"]','glim-system','WanderScout','{"website":"https://wanderscout.app/","x":"https://www.instagram.com/wanderscoutofficial"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781315400000,1781315400000),
('curated-norte-wallet','norte-wallet','Norte Wallet Intelligence','Find hidden card benefits, credits, and coverage without bank login.','Norte reads the fine print across credit cards and insurance policies to surface unused credits, purchase protections, and hidden benefits without connecting a bank account.','https://norteapp.io/',NULL,NULL,'https://norteapp.io/images/og/og-image-dashboard.png','Finance','["cards","benefits","finance"]','glim-system','Anonymous Maker','{"website":"https://norteapp.io/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781319000000,1781319000000),
('curated-ready-steady-find','ready-steady-find','Ready, Steady, Find!','A hidden-object supermarket sprint: find fast, tap faster, score big.','Ready, Steady, Find! is a fast hidden-object game where players hunt supermarket items against a clock. It is lightweight, visual, and instantly playable.','https://ready-steady-find.lovable.app/',NULL,NULL,'https://storage.googleapis.com/gpt-engineer-file-uploads/m2xgm8EDcKfl4FpyDfIfH60rjm03/social-images/social-1770293409996-Feature_Graphic_1024x500.png','Game','["game","hidden-object","arcade"]','glim-system','Anonymous Maker','{"website":"https://ready-steady-find.lovable.app/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781322600000,1781322600000),
('curated-wise-compass','wise-compass','The Wise Compass','Radical ethical fashion audits that crash-test brands on 15 criteria.','The Wise Compass audits fashion brands across climate, wages, tax, and supply-chain criteria so shoppers can spot greenwashing and find better alternatives.','https://www.thewisecompass.com/',NULL,NULL,'https://www.thewisecompass.com/og-image-wise-en.png','Other','["fashion","ethics","sustainability"]','glim-system','Anonymous Maker','{"website":"https://www.thewisecompass.com/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781326200000,1781326200000),
('curated-mindspark-study','mindspark-study','MindSpark Study','Upload materials and turn them into flashcards, quizzes, and study sets.','MindSpark Study converts uploaded notes and class materials into AI flashcards, quizzes, and study sets for faster exam prep.','https://mindsparkstudy.com/',NULL,NULL,'https://storage.googleapis.com/gpt-engineer-file-uploads/MqtjsRz5teXwn0yTrTJ9rizaP9l1/social-images/social-1778366532340-MindSpark_Study_OG_Image.webp','Education','["study","flashcards","education"]','glim-system','Nichelle','{"website":"https://mindsparkstudy.com/","x":"https://www.reddit.com/user/nichelle2571"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781329800000,1781329800000),
('curated-brand-studio','brand-studio','Brand Studio for Lovable','Generate a compact brand system, preview it, and export prompt-ready HTML.','Brand Studio for Lovable helps builders define colors, typography, and button styles, then preview and export a brand system that can be pasted back into app-builder prompts.','https://brand-studio-for.lovable.app/',NULL,NULL,'https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/6ea25bf0-8cf4-46a4-8618-589a94e536cd/id-preview-0087217d--aab4d1ca-da95-431e-a351-369e07dc50b0.lovable.app-1774533662355.png','DevTools','["design","branding","lovable"]','glim-system','Anonymous Maker','{"website":"https://brand-studio-for.lovable.app/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781333400000,1781333400000),
('curated-resumeagent','resumeagent','ResumeAgent','An ATS optimizer that fights AI hiring filters with AI.','ResumeAgent analyzes resumes against roles and helps candidates rewrite for ATS filters, keyword coverage, and clearer job fit.','https://resumeagentai.com/',NULL,NULL,'https://resumeagentai.com/og-image.jpg','Productivity','["resume","jobs","ai"]','glim-system','Josh Veryser','{"website":"https://resumeagentai.com/","x":"https://x.com/jnveryser"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781337000000,1781337000000),
('curated-cutlist-optimizer','cutlist-optimizer','CutList Optimizer','Nest panels and vector shapes onto sheets, then export for CNC or CAD.','CutList Optimizer lays rectangular parts and complex vector shapes onto material sheets, supports manual fine-tuning, and exports layouts for CNC/CAD workflows.','https://cutlayout.lovable.app/',NULL,NULL,'https://cutlayout.lovable.app/og-image.png','DevTools','["cnc","cad","optimizer"]','glim-system','Anonymous Maker','{"website":"https://cutlayout.lovable.app/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781340600000,1781340600000),
('curated-goldmine-ai','goldmine-ai','GoldMine AI','Turn any startup idea into market intelligence, ICPs, and lead lists.','GoldMine AI converts startup ideas into market research, customer profiles, competitor context, and qualified lead discovery for early founders.','https://www.goldmineai.io/',NULL,NULL,'https://www.goldmineai.io/lovable-uploads/goldmyne-logo-light.png','AI','["startup","research","leads"]','glim-system','Anonymous Maker','{"website":"https://www.goldmineai.io/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781344200000,1781344200000),
('curated-ninja-alert','ninja-alert','NinjaAlert','Email alerts when your child''s World Ninja League run order is posted.','NinjaAlert monitors World Ninja League run-order pages and sends parents an email when their child''s position appears, replacing manual refresh loops.','https://www.ninja-alert.com/',NULL,NULL,'https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/9cf06445-fb1b-40bd-acf3-37ace64be7d4/id-preview-26c44b5f--d0a59c73-fa79-4269-b891-02e290f4d2ad.lovable.app-1774018361998.png','Other','["sports","alerts","parents"]','glim-system','Anonymous Maker','{"website":"https://www.ninja-alert.com/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781347800000,1781347800000),
('curated-trackingpass','trackingpass','TrackingPass','Create digital loyalty cards for Apple Wallet and Google Wallet.','TrackingPass lets businesses launch digital loyalty cards customers can save to Apple Wallet or Google Wallet without downloading a separate app.','https://trackingpass.com/',NULL,NULL,'https://storage.googleapis.com/gpt-engineer-file-uploads/g8RHyVbXZ7gH025ziUjEmQ1JeCl1/social-images/social-1774845853360-Dise%C3%B1o_sin_t%C3%ADtulo_(5).webp','Productivity','["loyalty","wallet","business"]','glim-system','Anonymous Maker','{"website":"https://trackingpass.com/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781351400000,1781351400000),
('curated-svg-doodle','svg-doodle','SVG Doodle','Free editable SVG illustrations you can tweak and embed in seconds.','SVG Doodle is a web collection of editable SVG illustrations. Designers can browse, recolor, resize, and use assets directly in creative projects.','https://svgdoodles.com/',NULL,NULL,'https://svgdoodles.com/og-image.png','Content','["svg","design","illustrations"]','glim-system','Michael Andreuzza','{"website":"https://svgdoodles.com/","x":"https://x.com/mike_andreuzza"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781355000000,1781355000000),
('curated-vibe-coders-globe','vibe-coders-globe','The Vibe Coders Globe','A globe for people building with Lovable, Replit, Bubble, Framer, and AI tools.','The Vibe Coders Globe is a community map for the AI-builder movement: makers add themselves and see where other vibe coders are shipping from.','https://vibe-coders-globe-trotters.lovable.app/',NULL,NULL,'https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/daaef176-4a60-4c6b-abb5-1f0d9bd632a0/id-preview-45b8c068--36de6706-5612-450a-ad1a-2c909225bf60.lovable.app-1747296243456.png','Social','["community","map","vibe-coding"]','glim-system','Romain Laffitau','{"website":"https://vibe-coders-globe-trotters.lovable.app/","x":"https://x.com/RomainLaffitau"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781358600000,1781358600000),
('curated-great-taxi-assignment','great-taxi-assignment','The Great Taxi Assignment','The 2025 Vibe Coding Game Jam gold winner: chaotic taxi routing in Vibe City.','The Great Taxi Assignment won the 2025 Vibe Coding Game Jam gold prize. It drops players into a taxi-routing challenge built for the web under the jam rule that at least 80% of code/assets were AI-generated.','https://great-taxi-assignment.netlify.app/',NULL,NULL,'https://great-taxi-assignment.netlify.app/assets/social-preview.jpg','Game','["game","taxi","vibejam"]','glim-system','Tomas Bencko','{"website":"https://great-taxi-assignment.netlify.app/","x":"https://x.com/tomasbencko"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781362200000,1781362200000),
('curated-vibeware','vibeware','Vibeware','A microgame collection and 2025 Vibe Coding Game Jam silver winner.','Vibeware took silver in the 2025 Vibe Coding Game Jam with a fast microgame format, created for the web under AI-generated-code jam rules.','https://vibeware.vercel.app/',NULL,NULL,'https://vibeware.vercel.app/social-card.jpg','Game','["game","microgames","vibejam"]','glim-system','Matt Gordon','{"website":"https://vibeware.vercel.app/","x":"https://x.com/mattgordonxyz"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781365800000,1781365800000),
('curated-vector-tango','vector-tango','Vector Tango','A stylized vector action game and 2025 Vibe Coding Game Jam bronze winner.','Vector Tango won bronze in the 2025 Vibe Coding Game Jam, a web-first AI-assisted game jam where entries had to be mostly written with AI.','https://www.vector-tango.com/',NULL,NULL,'https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.vector-tango.com/','Game','["game","vector","vibejam"]','glim-system','Scobelverse','{"website":"https://www.vector-tango.com/","x":"https://x.com/scobelverse"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781369400000,1781369400000),
('curated-fly-pieter','fly-pieter','fly.pieter.com','A free-to-play browser MMO flight sim made with AI.','fly.pieter.com is Pieter Levels'' browser MMO flight sim, publicly described as 100% made with AI. It became one of the clearest commercial examples of vibe-coded games escaping novelty status.','https://fly.pieter.com/',NULL,'https://www.youtube.com/watch?v=7bC3SLyWy7w','https://fly.pieter.com/assets/fly_social_image.png?1234','Game','["flight-sim","mmo","ai"]','glim-system','Pieter Levels','{"website":"https://fly.pieter.com/","x":"https://x.com/levelsio"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781373000000,1781373000000),
('curated-outlit','outlit','Outlit','Customer context for AI agents that helps revenue teams structure better deals.','Outlit turns deal history into an AI-powered context layer for revenue teams, guiding reps and deal desks through pricing, approvals, and contract review. Semafor reported Leo Paz vibe-coded Outlit toward YC Demo Day.','https://www.outlit.ai/',NULL,NULL,'https://outlit.ai/opengraph-image.png?opengraph-image.06cddebb.png','AI','["sales","yc","agents"]','glim-system','Leo Paz','{"website":"https://www.outlit.ai/","x":"https://www.linkedin.com/in/leo-paz/"}',0,0,0,'web',NULL,'unclaimed',NULL,0,0,1781376600000,1781376600000);

INSERT OR IGNORE INTO posts (
  id, app_id, author_id, type, status, media_type,
  video_url, image_urls, image_captions, thumbnail_url, caption,
  like_count, comment_count, created_at
) VALUES
('post-curated-plinq','curated-plinq','glim-system','official','published','images',NULL,'["https://lp.plinq.com.br/plinq_pink_black.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://lp.plinq.com.br/"]','["Product preview image","Live homepage screenshot"]','https://lp.plinq.com.br/plinq_pink_black.png','Instant safety checks from public records for women in Brazil.',0,0,1781301060000),
('post-curated-betriqai','curated-betriqai','glim-system','official','published','images',NULL,'["https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/dc442780-12c8-4ea0-b285-6692f7af66fb/id-preview-ab9a2ca1--cedd0149-ff2c-4ff9-9b36-dae4ef207c95.lovable.app-1773807748624.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.betriqai.com/"]','["Product preview image","Live homepage screenshot"]','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/dc442780-12c8-4ea0-b285-6692f7af66fb/id-preview-ab9a2ca1--cedd0149-ff2c-4ff9-9b36-dae4ef207c95.lovable.app-1773807748624.png','AI sports predictions with match forecasts and real-time analytics.',0,0,1781304660000),
('post-curated-tastly','curated-tastly','glim-system','official','published','images',NULL,'["https://tastly.ai/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://tastly.ai/"]','["Product preview image","Live homepage screenshot"]','https://tastly.ai/og-image.png','An installable AI cookbook for saving, cooking, and sharing recipes.',0,0,1781308260000),
('post-curated-pathcraft','curated-pathcraft','glim-system','official','published','images',NULL,'["https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/9a1d4ca8-9af1-446a-92bc-512fecfa5f2c/id-preview-b2fb7158--ca4ac090-3d04-4f62-af7a-19d8544bda3e.lovable.app-1779745560137.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://roll-a-path.lovable.app/"]','["Product preview image","Live homepage screenshot"]','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/9a1d4ca8-9af1-446a-92bc-512fecfa5f2c/id-preview-b2fb7158--ca4ac090-3d04-4f62-af7a-19d8544bda3e.lovable.app-1779745560137.png','Roll dice, build the road, and race across a board you invented.',0,0,1781311860000),
('post-curated-wanderscout','curated-wanderscout','glim-system','official','published','images',NULL,'["https://wanderscout.app/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://wanderscout.app/"]','["Product preview image","Live homepage screenshot"]','https://wanderscout.app/og-image.png','AI travel search that finds destinations matching your constraints.',0,0,1781315460000),
('post-curated-norte-wallet','curated-norte-wallet','glim-system','official','published','images',NULL,'["https://norteapp.io/images/og/og-image-dashboard.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://norteapp.io/"]','["Product preview image","Live homepage screenshot"]','https://norteapp.io/images/og/og-image-dashboard.png','Find hidden card benefits, credits, and coverage without bank login.',0,0,1781319060000),
('post-curated-ready-steady-find','curated-ready-steady-find','glim-system','official','published','images',NULL,'["https://storage.googleapis.com/gpt-engineer-file-uploads/m2xgm8EDcKfl4FpyDfIfH60rjm03/social-images/social-1770293409996-Feature_Graphic_1024x500.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://ready-steady-find.lovable.app/"]','["Product preview image","Live homepage screenshot"]','https://storage.googleapis.com/gpt-engineer-file-uploads/m2xgm8EDcKfl4FpyDfIfH60rjm03/social-images/social-1770293409996-Feature_Graphic_1024x500.png','A hidden-object supermarket sprint: find fast, tap faster, score big.',0,0,1781322660000),
('post-curated-wise-compass','curated-wise-compass','glim-system','official','published','images',NULL,'["https://www.thewisecompass.com/og-image-wise-en.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.thewisecompass.com/"]','["Product preview image","Live homepage screenshot"]','https://www.thewisecompass.com/og-image-wise-en.png','Radical ethical fashion audits that crash-test brands on 15 criteria.',0,0,1781326260000),
('post-curated-mindspark-study','curated-mindspark-study','glim-system','official','published','images',NULL,'["https://storage.googleapis.com/gpt-engineer-file-uploads/MqtjsRz5teXwn0yTrTJ9rizaP9l1/social-images/social-1778366532340-MindSpark_Study_OG_Image.webp","https://image.thum.io/get/width/900/crop/1600/noanimate/https://mindsparkstudy.com/"]','["Product preview image","Live homepage screenshot"]','https://storage.googleapis.com/gpt-engineer-file-uploads/MqtjsRz5teXwn0yTrTJ9rizaP9l1/social-images/social-1778366532340-MindSpark_Study_OG_Image.webp','Upload materials and turn them into flashcards, quizzes, and study sets.',0,0,1781329860000),
('post-curated-brand-studio','curated-brand-studio','glim-system','official','published','images',NULL,'["https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/6ea25bf0-8cf4-46a4-8618-589a94e536cd/id-preview-0087217d--aab4d1ca-da95-431e-a351-369e07dc50b0.lovable.app-1774533662355.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://brand-studio-for.lovable.app/"]','["Product preview image","Live homepage screenshot"]','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/6ea25bf0-8cf4-46a4-8618-589a94e536cd/id-preview-0087217d--aab4d1ca-da95-431e-a351-369e07dc50b0.lovable.app-1774533662355.png','Generate a compact brand system, preview it, and export prompt-ready HTML.',0,0,1781333460000),
('post-curated-resumeagent','curated-resumeagent','glim-system','official','published','images',NULL,'["https://resumeagentai.com/og-image.jpg","https://image.thum.io/get/width/900/crop/1600/noanimate/https://resumeagentai.com/"]','["Product preview image","Live homepage screenshot"]','https://resumeagentai.com/og-image.jpg','An ATS optimizer that fights AI hiring filters with AI.',0,0,1781337060000),
('post-curated-cutlist-optimizer','curated-cutlist-optimizer','glim-system','official','published','images',NULL,'["https://cutlayout.lovable.app/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://cutlayout.lovable.app/"]','["Product preview image","Live homepage screenshot"]','https://cutlayout.lovable.app/og-image.png','Nest panels and vector shapes onto sheets, then export for CNC or CAD.',0,0,1781340660000),
('post-curated-goldmine-ai','curated-goldmine-ai','glim-system','official','published','images',NULL,'["https://www.goldmineai.io/lovable-uploads/goldmyne-logo-light.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.goldmineai.io/"]','["Product preview image","Live homepage screenshot"]','https://www.goldmineai.io/lovable-uploads/goldmyne-logo-light.png','Turn any startup idea into market intelligence, ICPs, and lead lists.',0,0,1781344260000),
('post-curated-ninja-alert','curated-ninja-alert','glim-system','official','published','images',NULL,'["https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/9cf06445-fb1b-40bd-acf3-37ace64be7d4/id-preview-26c44b5f--d0a59c73-fa79-4269-b891-02e290f4d2ad.lovable.app-1774018361998.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.ninja-alert.com/"]','["Product preview image","Live homepage screenshot"]','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/9cf06445-fb1b-40bd-acf3-37ace64be7d4/id-preview-26c44b5f--d0a59c73-fa79-4269-b891-02e290f4d2ad.lovable.app-1774018361998.png','Email alerts when your child''s World Ninja League run order is posted.',0,0,1781347860000),
('post-curated-trackingpass','curated-trackingpass','glim-system','official','published','images',NULL,'["https://storage.googleapis.com/gpt-engineer-file-uploads/g8RHyVbXZ7gH025ziUjEmQ1JeCl1/social-images/social-1774845853360-Dise%C3%B1o_sin_t%C3%ADtulo_(5).webp","https://image.thum.io/get/width/900/crop/1600/noanimate/https://trackingpass.com/"]','["Product preview image","Live homepage screenshot"]','https://storage.googleapis.com/gpt-engineer-file-uploads/g8RHyVbXZ7gH025ziUjEmQ1JeCl1/social-images/social-1774845853360-Dise%C3%B1o_sin_t%C3%ADtulo_(5).webp','Create digital loyalty cards for Apple Wallet and Google Wallet.',0,0,1781351460000),
('post-curated-svg-doodle','curated-svg-doodle','glim-system','official','published','images',NULL,'["https://svgdoodles.com/og-image.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://svgdoodles.com/"]','["Product preview image","Live homepage screenshot"]','https://svgdoodles.com/og-image.png','Free editable SVG illustrations you can tweak and embed in seconds.',0,0,1781355060000),
('post-curated-vibe-coders-globe','curated-vibe-coders-globe','glim-system','official','published','images',NULL,'["https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/daaef176-4a60-4c6b-abb5-1f0d9bd632a0/id-preview-45b8c068--36de6706-5612-450a-ad1a-2c909225bf60.lovable.app-1747296243456.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://vibe-coders-globe-trotters.lovable.app/"]','["Product preview image","Live homepage screenshot"]','https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/daaef176-4a60-4c6b-abb5-1f0d9bd632a0/id-preview-45b8c068--36de6706-5612-450a-ad1a-2c909225bf60.lovable.app-1747296243456.png','A globe for people building with Lovable, Replit, Bubble, Framer, and AI tools.',0,0,1781358660000),
('post-curated-great-taxi-assignment','curated-great-taxi-assignment','glim-system','official','published','images',NULL,'["https://great-taxi-assignment.netlify.app/assets/social-preview.jpg","https://image.thum.io/get/width/900/crop/1600/noanimate/https://great-taxi-assignment.netlify.app/"]','["Product preview image","Live homepage screenshot"]','https://great-taxi-assignment.netlify.app/assets/social-preview.jpg','The 2025 Vibe Coding Game Jam gold winner: chaotic taxi routing in Vibe City.',0,0,1781362260000),
('post-curated-vibeware','curated-vibeware','glim-system','official','published','images',NULL,'["https://vibeware.vercel.app/social-card.jpg","https://image.thum.io/get/width/900/crop/1600/noanimate/https://vibeware.vercel.app/"]','["Product preview image","Live homepage screenshot"]','https://vibeware.vercel.app/social-card.jpg','A microgame collection and 2025 Vibe Coding Game Jam silver winner.',0,0,1781365860000),
('post-curated-vector-tango','curated-vector-tango','glim-system','official','published','images',NULL,'["https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.vector-tango.com/"]','["Live homepage screenshot"]','https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.vector-tango.com/','A stylized vector action game and 2025 Vibe Coding Game Jam bronze winner.',0,0,1781369460000),
('post-curated-fly-pieter','curated-fly-pieter','glim-system','official','published','images',NULL,'["https://fly.pieter.com/assets/fly_social_image.png?1234","https://image.thum.io/get/width/900/crop/1600/noanimate/https://fly.pieter.com/"]','["Product preview image","Live homepage screenshot"]','https://fly.pieter.com/assets/fly_social_image.png?1234','A free-to-play browser MMO flight sim made with AI.',0,0,1781373060000),
('post-curated-outlit','curated-outlit','glim-system','official','published','images',NULL,'["https://outlit.ai/opengraph-image.png?opengraph-image.06cddebb.png","https://image.thum.io/get/width/900/crop/1600/noanimate/https://www.outlit.ai/"]','["Product preview image","Live homepage screenshot"]','https://outlit.ai/opengraph-image.png?opengraph-image.06cddebb.png','Customer context for AI agents that helps revenue teams structure better deals.',0,0,1781376660000);
